#version 430

#define GROUP_SIZE 256

layout( local_size_x = GROUP_SIZE ) in;

layout( push_constant ) uniform params {
  uint len;
  uint depth;
} PushConstant;

layout(std430, binding = 0) buffer a
{
    float sum[];
};

layout(std430, binding = 1) buffer Res
{
    float res[];
};

void main() 
{
    uint idx = gl_WorkGroupID.x;
    uint global_idx = gl_GlobalInvocationID.x;

    if (global_idx < PushConstant.len) 
    {
        res[global_idx] += sum[idx];
    }
}